### ISSUE TITLE
Why is the N_ref map half red and half green？

### ISSUE THREAD

**Issue by anewusername77** [Brummi/derender3d#6]
I tried this code and saved `normal map from depth` and `refinement normal map`, like this:
normal from depth map:
![1a8ad9e6-572d-439b-9822-67fc6adbc03e](https://user-images.githubusercontent.com/23047054/181501460-291a3331-01b5-4a45-b77c-02fdc7eac17e.jpg)
normal from network:
![0c5ba67f-4361-43be-b9b0-834c758441c6](https://user-images.githubusercontent.com/23047054/181501508-88c7a877-d00a-4405-8da4-83ff294b5ffd.jpg)
I'm confused, why is the refinement normal map half red half green? looking forward to your response!

**Comment by Brummi** [comment]
Hi,
thanks for being interested in out code!
Sometimes the depth prediction network struggles to give a good initial depth estimate. Therefore, the normal from depth map is rather flat. Consequently, the normal refinement network has to correct it. The reason it is red / green is because of the x-axis (= red channel) value of the normals is mirrored.

**Comment by anewusername77** [comment]
thank you so much!
